-- update-2022-05-01.sql for Rourke 2017

CREATE TABLE IF NOT EXISTS `formRourke2017` (
   `ID` int(10) NOT NULL AUTO_INCREMENT,
   `demographic_no` int(10),
   `c_male` varchar(2),
   `c_female` varchar(2),
   `provider_no` varchar(6),
   `formCreated` date,
   `formEdited` timestamp NOT NULL ON UPDATE CURRENT_TIMESTAMP,
   `c_lastVisited` char(3),
   `c_birthRemarks` text,
   `c_riskFactors` text,
   `c_famHistory` text,
   `c_pName` varchar(60),
   `c_birthDate` date,
   `c_length` varchar(6),
   `c_headCirc` varchar(6),
   `c_birthWeight` varchar(7),
   `c_dischargeWeight` varchar(7),
   `c_fsa` char(3),
   `start_of_gestation` DATE,
   `c_APGAR1min` int(11),
   `c_APGAR5min` int(11),
   `p1_date1w` date,
   `p1_date2w` date,
   `p1_date1m` date,
   `p1_ht1w` varchar(5),
   `p1_wt1w` varchar(5),
   `p1_hc1w` varchar(5),
   `p1_ht2w` varchar(5),
   `p1_wt2w` varchar(5),
   `p1_hc2w` varchar(5),
   `p1_ht1m` varchar(5),
   `p1_wt1m` varchar(5),
   `p1_hc1m` varchar(5),
   `p1_pConcern1w` text,
   `p1_pConcern2w` text,
   `p1_pConcern1m` text,
   `p1_development1w` text,
   `p1_development2w` text,
   `p1_development1m` text,
   `p1_problems1w` text,
   `p1_problems2w` text,
   `p1_problems1m` text,
   `p1_signature2w` varchar(250),
   `p2_date2m` date,
   `p2_date4m` date,
   `p2_date6m` date,
   `p2_ht2m` varchar(5),
   `p2_wt2m` varchar(5),
   `p2_hc2m` varchar(5),
   `p2_ht4m` varchar(5),
   `p2_wt4m` varchar(5),
   `p2_hc4m` varchar(5),
   `p2_ht6m` varchar(5),
   `p2_wt6m` varchar(5),
   `p2_hc6m` varchar(5),
   `p2_pConcern2m` text,
   `p2_pConcern4m` text,
   `p2_pConcern6m` text,
   `p2_nutrition2m` text,
   `p2_nutrition4m` text,
   `p2_development2m` text,
   `p2_development4m` text,
   `p2_development6m` text,
   `p2_problems2m` text,
   `p2_problems4m` text,
   `p2_problems6m` text,
   `p2_signature2m` varchar(250),
   `p2_signature4m` varchar(250),
   `p3_date9m` date,
   `p3_date12m` date,
   `p3_date15m` date,
   `p3_ht9m` varchar(5),
   `p3_wt9m` varchar(5),
   `p3_hc9m` varchar(5),
   `p3_ht12m` varchar(5),
   `p3_wt12m` varchar(5),
   `p3_hc12m` varchar(5),
   `p3_ht15m` varchar(5),
   `p3_wt15m` varchar(5),
   `p3_hc15m` varchar(5),
   `p3_pConcern9m` text,
   `p3_pConcern12m` text,
   `p3_pConcern15m` text,
   `p3_nutrition12m` text,
   `p3_nutrition15m` text,
   `p3_development9m` text,
   `p3_development12m` text,
   `p3_development15m` text,
   `p3_problems9m` text,
   `p3_problems12m` text,
   `p3_problems15m` text,
   `p3_signature9m` varchar(250),
   `p3_signature12m` varchar(250),
   `p3_signature15m` varchar(250),
   `p4_date18m` date,
   `p4_date24m` date,
   `p4_date48m` date,
   `p4_ht18m` varchar(5),
   `p4_wt18m` varchar(5),
   `p4_hc18m` varchar(5),
   `p4_ht24m` varchar(5),
   `p4_wt24m` varchar(5),
   `p4_hc24m` varchar(5),
   `p4_ht48m` varchar(5),
   `p4_bmi24m` varchar(5),
   `p4_bmi48m` varchar(10),
   `p4_wt48m` varchar(5),
   `p4_pConcern18m` text,
   `p4_pConcern24m` text,
   `p4_pConcern48m` text,
   `p4_problems18m` text,
   `p4_problems24m` text,
   `p4_problems48m` text,
   `p4_signature18m` varchar(250),
   `p4_signature24m` varchar(250),
   `p4_signature48m` varchar(250),
   `p1_signature1w` varchar(250),
   `p1_signature1m` varchar(250),
   `p2_signature6m` varchar(250),
   `p1_pNutrition1w` text,
   `p1_pNutrition2w` text,
   `p1_pNutrition1m` text,
   `p1_education1w` text,
   `p1_education2w` text,
   `p1_education1m` text,
   `p1_pPhysical1w` text,
   `p1_pPhysical2w` text,
   `p1_pPhysical1m` text,
   `p1_immunization1w` text,
   `p1_immunization2w` text,
   `p1_immunization1m` text,
   `p2_nutrition6m` text,
   `p2_education2m` text,
   `p2_education4m` text,
   `p2_education6m` text,
   `p2_physical2m` text,
   `p2_physical4m` text,
   `p2_physical6m` text,
   `p2_immunization6m` text,
   `p3_nutrition9m` text,
   `p3_education9m` text,
   `p3_education12m` text,
   `p3_education15m` text,
   `p3_physical9m` text,
   `p3_physical12m` text,
   `p3_physical15m` text,
   `p4_nutrition18m` text,
   `p4_nutrition24m` text,
   `p4_nutrition48m` text,
   `p4_education18m` text,
   `p4_education24m` text,
   `p4_education48m` text,
   `p4_development18m` text,
   `p4_development24m` text,
   `p4_development48m` text,
   `p4_development36m` text,
   `p4_development60m` text,
   `p4_physical18m` text,
   `p4_physical24m` text,
   `p4_physical48m` text,
   `p4_nippisingattained` text,
   PRIMARY KEY (`ID`),
   KEY `formRourke2017_demographic_no` (`demographic_no`)
 ); 
 
CREATE TABLE IF NOT EXISTS `form_boolean_value` (
   `form_name` varchar(50) NOT NULL,
   `form_id` int(10) NOT NULL,
   `field_name` varchar(50) NOT NULL,
   `value` tinyint(1),
   PRIMARY KEY (`form_name`,`form_id`,`field_name`)
 );
 
INSERT INTO encounterForm (form_name, form_value, form_table, hidden) 
VALUES ('Rourke2017', '../form/formrourke2017complete.jsp?demographic_no=', 'formRourke2017', 0);
