insert into measurementType (type, typeDisplayName, typeDescription, measuringInstruction, createDate, validation) values
('UMS', 'Urinary Microalbumin Screen', 'Urinary Microalbumin Screen', 'Records the value of the Urinary Microalbumin test: mg/L', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1BF', 'FEV1 (before puff)', 'FEV1 (before puff)', 'Forced Expiratory Volume: the volume of air that has been exhaled by the patient at the end of the first second of forced expiration', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FVCBF', 'FVC (before puff)', 'FVC (before puff)', 'Forced Vital Capacity: the volume of air that has been forcibly and maximally exhaled out by the patient until no more can be expired', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1PCBF', 'FEV1% (before puff)', 'FEV1% (before puff)', 'The ratio of FEV1 to FVC calculated for the patient', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1PRE', 'FEV1 predicted', 'FEV1 predicted', 'The FEV1 calculated in the population with similar characteristics (e.g. height, age, sex, race, weight, etc.)', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FVCPRE', 'FVC predicted', 'FVC predicted', 'Forced Vital Capacity predicted: calculated in the population with similar characteristics (height, age, sex, and sometimes race and weight)', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1PCPRE', 'FEV1% predicted', 'FEV1% predicted', 'The ratio of FEV1 predicted to FVC predicted, calculated in the population with similar characteristics (height, age, sex, and sometimes race and weight)', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1PCOFPREBF', 'FEV1% of predicted (before puff)', 'FEV1% of predicted (before puff)', 'FEV1% (before puff) of the patient divided by the average FEV1% predicted in the population with similar characteristics (e.g. height, age, sex, race, weight, etc.)', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FVCRTBF', 'FVC ratio (before puff)', 'FVC ratio (before puff)', 'FVC actual (before puff) / FVC predicted', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1FVCRTBF', 'FEV1 / FVC ratio (before puff)', 'FEV1 / FVC ratio (before puff)', 'FEV1 / FVC (before puff) actual divided by FEV1 / FVC predicted', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('PEFRBF', 'PEF personal (before puff)', 'PEF personal (before puff)', 'Peak Expiratory Flow: the maximal flow (or speed) achieved during the maximally forced expiration initiated at full inspiration', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1AFT', 'FEV1 (after puff)', 'FEV1 (after puff)', 'Forced Expiratory Volume: the volume of air that has been exhaled by the patient at the end of the first second of forced expiration', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FVCAFT', 'FVC (after puff)', 'FVC (after puff)', 'Forced Vital Capacity: the volume of air that has been forcibly and maximally exhaled out by the patient until no more can be expired', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1PCAFT', 'FEV1% (after puff)', 'FEV1% (after puff)', 'The ratio of FEV1 to FVC calculated for the patient', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1PCOFPREAFT', 'FEV1% of predicted (after puff)', 'FEV1% of predicted (after puff)', 'FEV1% (after puff) of the patient divided by the average FEV1% predicted in the population with similar characteristics (e.g. height, age, sex, race, weight, etc.)', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FVCRTAFT', 'FVC ratio (after puff)', 'FVC ratio (after puff)', 'FVC actual (after puff) / FVC predicted', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('FEV1FVCRTAFT', 'FEV1 / FVC ratio (after puff)', 'FEV1 / FVC ratio (after puff)', 'FEV1 / FVC (after puff) actual divided by FEV1 / FVC predicted', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('PEFRAFT', 'PEF personal (after puff)', 'PEF personal (after puff)', 'Peak Expiratory Flow: the maximal flow (or speed) achieved during the maximally forced expiration initiated at full inspiration', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('ANELV', 'Asthma: # Of Exacerbations Requiring Clinical Evaluation since last assessment', 'Asthma: # Of Exacerbations Requiring Clinical Evaluation since last assessment', 'The number of exacerbations since the last assessment requiring clinical evaluations reported by the patient', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('CNOLE', 'COPD: # of Exacerbations since last assessment', 'COPD: # of Exacerbations since last assessment', 'The number of exacerbations due to COPD since last visit, as reported by the patient', now(),
(select id from validations where name='Numeric Value greater than or equal to 0' limit 1)),
('WHE', 'Wheezing', 'Wheezing', 'Records whether the patient is wheezing or not', now(),
(select id from validations where name='Yes/No' limit 1)),
('HFMR', 'HF Medication Review', 'Heart Failure Medication Review', 'Records whether medication adherence for Heart Failure purpose has been discussed with the patient', now(),
(select id from validations where name='Yes/No' limit 1));

