ALTER TABLE LookupList ADD COLUMN `listTitle` varchar(255) AFTER `id`;

REPLACE into encounterForm values ('Gynae Form', '../form/formgynae.jsp?demographic_no=', 'formgyane', '0');

CREATE TABLE IF NOT EXISTS  `formgyane` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `visitDate` date DEFAULT NULL,
  `demographic_no` int(11) DEFAULT NULL,
  `comments` text,
  `fromDate` date DEFAULT NULL,
  `toDate` date DEFAULT NULL,
  `bpi_age` varchar(5) DEFAULT NULL,
  `bpi_g` varchar(20) DEFAULT NULL,
  `bpi_t` varchar(20) DEFAULT NULL,
  `bpi_p` varchar(20) DEFAULT NULL,
  `bpi_a` varchar(20) DEFAULT NULL,
  `bpi_l` varchar(20) DEFAULT NULL,
  `bpi_minlength` varchar(5) DEFAULT NULL,
  `bpi_maxlength` varchar(5) DEFAULT NULL,
  `bpi_mininterval` varchar(5) DEFAULT NULL,
  `bpi_maxinterval` varchar(5) DEFAULT NULL,
  `bpi_amountpads` varchar(5) DEFAULT NULL,
  `bpi_current_contra_method` varchar(10) DEFAULT NULL,
  `bpi_lmp_n` tinyint(1) DEFAULT NULL,
  `bpi_lmp_abn` tinyint(1) DEFAULT NULL,
  `bpi_lastpap_n` tinyint(1) DEFAULT NULL,
  `bpi_lastpap_abn` tinyint(1) DEFAULT NULL,
  `bpi_lastmemo_n` tinyint(1) DEFAULT NULL,
  `bpi_lastmemo_abn` tinyint(1) DEFAULT NULL,
  `obs_svd` varchar(10) DEFAULT NULL,
  `obs_cs` varchar(10) DEFAULT NULL,
  `obs_notes` text,
  `fmh_brest` tinyint(1) DEFAULT NULL,
  `fmh_gynaecological` tinyint(1) DEFAULT NULL,
  `fmh_bowel` tinyint(1) DEFAULT NULL,
  `fmh_osteoporosis` tinyint(1) DEFAULT NULL,
  `fmh_notes` text,
  `pmh_wt_loss` tinyint(1) DEFAULT NULL,
  `pmh_tuberculosis` tinyint(1) DEFAULT NULL,
  `pmh_urinary` tinyint(1) DEFAULT NULL,
  `pmh_diabetes` tinyint(1) DEFAULT NULL,
  `pmh_headaches` tinyint(1) DEFAULT NULL,
  `pmh_jaundice_hep` tinyint(1) DEFAULT NULL,
  `pmh_anemia_blood` tinyint(1) DEFAULT NULL,
  `pmh_cancer` tinyint(1) DEFAULT NULL,
  `pmh_heart_disease` tinyint(1) DEFAULT NULL,
  `pmh_gall_bladder` tinyint(1) DEFAULT NULL,
  `pmh_blood_trans` tinyint(1) DEFAULT NULL,
  `pmh_epilepsy` tinyint(1) DEFAULT NULL,
  `pmh_hypertension` tinyint(1) DEFAULT NULL,
  `pmh_hernia_ulser` tinyint(1) DEFAULT NULL,
  `pmh_varicose` tinyint(1) DEFAULT NULL,
  `pmh_arthritis` tinyint(1) DEFAULT NULL,
  `pmh_respiratory` tinyint(1) DEFAULT NULL,
  `pmh_bowel_disorder` tinyint(1) DEFAULT NULL,
  `pmh_phlebitis` tinyint(1) DEFAULT NULL,
  `pmh_osteoporosis` tinyint(1) DEFAULT NULL,
  `pmh_breast_dis` tinyint(1) DEFAULT NULL,
  `pmh_kidney` tinyint(1) DEFAULT NULL,
  `pmh_thyroid` tinyint(1) DEFAULT NULL,
  `pmh_std` tinyint(1) DEFAULT NULL,
  `pmh_notes` text,
  `psh_year` varchar(10) DEFAULT NULL,
  `psh_operation_illness` varchar(20) DEFAULT NULL,
  `cm_current_medication` text,
  `habits_cigarettes` tinyint(1) DEFAULT NULL,
  `habits_cigperday` varchar(5) DEFAULT NULL,
  `habits_alcohol` tinyint(1) DEFAULT NULL,
  `habits_alcoholperweek` varchar(5) DEFAULT NULL,
  `habits_streetdrugs` tinyint(1) DEFAULT NULL,
  `habits_notes` text,
  `allergies` text,
  `additional_notes` text,
  `rfr_abn_pap` tinyint(1) DEFAULT NULL,
  `rfr_infertility` tinyint(1) DEFAULT NULL,
  `rfr_menorrhagia` tinyint(1) DEFAULT NULL,
  `rfr_contraceptivehist` tinyint(1) DEFAULT NULL,
  `rfr_irregularperiods` tinyint(1) DEFAULT NULL,
  `rfr_ovariancyst` tinyint(1) DEFAULT NULL,
  `rfr_fibroids` tinyint(1) DEFAULT NULL,
  `rfr_menopause` tinyint(1) DEFAULT NULL,
  `rfr_pelvicpain` tinyint(1) DEFAULT NULL,
  `rfr_incontinence` tinyint(1) DEFAULT NULL,
  `abpap_inflam` tinyint(1) DEFAULT NULL,
  `abpap_lgsil` tinyint(1) DEFAULT NULL,
  `abpap_previouscolpo_y` tinyint(1) DEFAULT NULL,
  `abpap_previouscolpo_n` tinyint(1) DEFAULT NULL,
  `abpap_ascus` tinyint(1) DEFAULT NULL,
  `abpap_hgsil` tinyint(1) DEFAULT NULL,
  `abpap_previoustx_y` tinyint(1) DEFAULT NULL,
  `abpap_previoustx_n` tinyint(1) DEFAULT NULL,
  `pch_bcp` tinyint(1) DEFAULT NULL,
  `pch_nuvo_ring` tinyint(1) DEFAULT NULL,
  `pch_IUD` tinyint(1) DEFAULT NULL,
  `pch_condoms` tinyint(1) DEFAULT NULL,
  `pch_rhythmmethod` varchar(11) DEFAULT NULL,
  `pch_vasectomy` tinyint(1) DEFAULT NULL,
  `pch_depo_proverainj` tinyint(1) DEFAULT NULL,
  `pch_tuballigation` tinyint(1) DEFAULT NULL,
  `pch_withdrawal` tinyint(1) DEFAULT NULL,
  `pch_evrapatch` tinyint(1) DEFAULT NULL,
  `pch_foam` tinyint(1) DEFAULT NULL,
  `pch_nobirthcontrolused` tinyint(1) DEFAULT NULL,
  `pch_notes` text,
  `fibro_years` varchar(10) DEFAULT NULL,
  `fibro_menorrhagia_y` tinyint(1) DEFAULT NULL,
  `fibro_menorrhagia_n` tinyint(1) DEFAULT NULL,
  `fibro_pelvicpressure_y` tinyint(1) DEFAULT NULL,
  `fibro_pelvicpressure_n` tinyint(1) DEFAULT NULL,
  `fibro_pelvicpain_y` tinyint(1) DEFAULT NULL,
  `fibro_pelvicpain_n` tinyint(1) DEFAULT NULL,
  `ultrasound_fibroids` varchar(20) DEFAULT NULL,
  `ultrasound_size` varchar(20) DEFAULT NULL,
  `ultrasound_cm` varchar(20) DEFAULT NULL,
  `incontinence_years` varchar(10) DEFAULT NULL,
  `incontinence_frequency_y` tinyint(1) DEFAULT NULL,
  `incontinence_frequency_n` tinyint(1) DEFAULT NULL,
  `incontinence_urgency_y` tinyint(1) DEFAULT NULL,
  `incontinence_urgency_n` tinyint(1) DEFAULT NULL,
  `incontinenc_nocturia_y` tinyint(1) DEFAULT NULL,
  `incontinenc_nocturia_n` tinyint(1) DEFAULT NULL,
  `incontinenc_dysuria_y` tinyint(1) DEFAULT NULL,
  `incontinenc_dysuria_n` tinyint(1) DEFAULT NULL,
  `incontinenc_sui_y` tinyint(1) DEFAULT NULL,
  `incontinenc_sui_n` tinyint(1) DEFAULT NULL,
  `infertility_years` varchar(10) DEFAULT NULL,
  `infertility_sperm_analysis_y` tinyint(1) DEFAULT NULL,
  `infertility_sperm_analysis_n` tinyint(1) DEFAULT NULL,
  `infertility_partnerhas_children_y` tinyint(1) DEFAULT NULL,
  `infertility_partnerhas_children_n` tinyint(1) DEFAULT NULL,
  `infertility_std_y` tinyint(1) DEFAULT NULL,
  `infertility_std_n` tinyint(1) DEFAULT NULL,
  `infertility_iud_y` tinyint(1) DEFAULT NULL,
  `infertility_iud_n` tinyint(1) DEFAULT NULL,
  `infertility_pid_y` tinyint(1) DEFAULT NULL,
  `infertility_pid_n` tinyint(1) DEFAULT NULL,
  `irregularperiods_hirsutism_y` tinyint(1) DEFAULT NULL,
  `irregularperiods_hirsutism_n` tinyint(1) DEFAULT NULL,
  `irregularperiods_acnea_y` tinyint(1) DEFAULT NULL,
  `irregularperiods_acnea_n` tinyint(1) DEFAULT NULL,
  `irregularperiods_wtgain_lbs` varchar(10) DEFAULT NULL,
  `irregularperiods_wtgain_months` varchar(10) DEFAULT NULL,
  `irregularperiods_amenorrhea` varchar(10) DEFAULT NULL,
  `irregularperiods_extremeexercise_y` tinyint(1) DEFAULT NULL,
  `irregularperiods_extremeexercise_n` tinyint(1) DEFAULT NULL,
  `irregularperiods_galactorrhea_y` tinyint(1) DEFAULT NULL,
  `irregularperiods_galactorrhea_n` tinyint(1) DEFAULT NULL,
  `menopause_amenorrhea_months` varchar(2) DEFAULT NULL,
  `menopause_hotflashes_y` tinyint(1) DEFAULT NULL,
  `menopause_hotflashes_n` tinyint(1) DEFAULT NULL,
  `menopause_insomnia_y` tinyint(1) DEFAULT NULL,
  `menopause_insomnia_n` tinyint(1) DEFAULT NULL,
  `menopause_nightsweats_y` tinyint(1) DEFAULT NULL,
  `menopause_nightsweats_n` tinyint(1) DEFAULT NULL,
  `menopause_vaginaldryness_y` tinyint(1) DEFAULT NULL,
  `menopause_vaginaldryness_n` tinyint(1) DEFAULT NULL,
  `menopause_depressionanxiety_y` tinyint(1) DEFAULT NULL,
  `menopause_depressionanxiety_n` tinyint(1) DEFAULT NULL,
  `menorrhagia_periods_length` varchar(5) DEFAULT NULL,
  `menorrhagia_periods_length_days` varchar(5) DEFAULT NULL,
  `menorrhagia_periods_interval` varchar(10) DEFAULT NULL,
  `menorrhagia_periods_interval_days` varchar(5) DEFAULT NULL,
  `menorrhagia_periods_amountspads_hrs` varchar(5) DEFAULT NULL,
  `menorrhagia_imb_y` tinyint(1) DEFAULT NULL,
  `menorrhagia_imb_n` tinyint(1) DEFAULT NULL,
  `menorrhagia_pcb_y` tinyint(1) DEFAULT NULL,
  `menorrhagia_pcb_n` tinyint(1) DEFAULT NULL,
  `ovariancyst_years` varchar(10) DEFAULT NULL,
  `ovariancyst_pain_y` tinyint(1) DEFAULT NULL,
  `ovariancyst_pain_n` tinyint(1) DEFAULT NULL,
  `ovariancyst_ultrasound_right` tinyint(1) DEFAULT NULL,
  `ovariancyst_ultrasound_left` tinyint(1) DEFAULT NULL,
  `ovariancyst_ultrasound_size` varchar(5) DEFAULT NULL,
  `characteristics` text,
  `pelvicpain_dysmenorrhea_y` tinyint(1) DEFAULT NULL,
  `pelvicpain_dysmenorrhea_n` tinyint(1) DEFAULT NULL,
  `pelvicpain_dyspareunia_y` tinyint(1) DEFAULT NULL,
  `pelvicpain_dyspareunia_n` tinyint(1) DEFAULT NULL,
  `pelvicpain_dyschezia_y` tinyint(1) DEFAULT NULL,
  `pelvicpain_dyschezia_n` tinyint(1) DEFAULT NULL,
  `pelvicpain_location_rlq_y` tinyint(1) DEFAULT NULL,
  `pelvicpain_location_rlq_n` tinyint(1) DEFAULT NULL,
  `pelvicpain_location_llq_y` tinyint(1) DEFAULT NULL,
  `pelvicpain_location_llq_n` tinyint(1) DEFAULT NULL,
  `pelvicpain_suprapublic` tinyint(1) DEFAULT NULL,
  `pelvicpain_timingof_pain` tinyint(1) DEFAULT NULL,
  `previousinvestigations_bloodwork` tinyint(1) DEFAULT NULL,
  `previousinvestigations_hb` varchar(10) DEFAULT NULL,
  `previousinvestigations_hormones` varchar(10) DEFAULT NULL,
  `previousinvestigations_ultrasound` tinyint(1) DEFAULT NULL,
  `previousinvestigations_notes` text,
  `physicalexam_breasts_n` tinyint(1) DEFAULT NULL,
  `physicalexam_breasts_abn` tinyint(1) DEFAULT NULL,
  `physicalexam_abdomen_n` tinyint(1) DEFAULT NULL,
  `physicalexam_abdomen_abn` tinyint(1) DEFAULT NULL,
  `physicalexam_notes` text,
  `gynaecologicalexam_genitalia_n` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_genitalia_abn` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_vaginal_n` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_vaginal_abn` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_cervix_n` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_cervix_abn` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_rectum_n` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_rectum_abn` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_uterus_n` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_uterus_abn` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_position_av` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_position_rv` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_size` varchar(10) DEFAULT NULL,
  `gynaecologicalexam_adnexa_left_n` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_adnexa_left_abn` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_adnexa_right_n` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_adnexa_right_abn` tinyint(1) DEFAULT NULL,
  `gynaecologicalexam_notes` text,
  `investigations_ultrasound` tinyint(1) DEFAULT NULL,
  `investigations_bloodwork` tinyint(1) DEFAULT NULL,
  `investigations_cbcferritin` tinyint(1) DEFAULT NULL,
  `investigations_hormprofile` tinyint(1) DEFAULT NULL,
  `investigations_sis` tinyint(1) DEFAULT NULL,
  `investigations_tubalpatency` tinyint(1) DEFAULT NULL,
  `investigations_menstrualcal` tinyint(1) DEFAULT NULL,
  `investigations_bbt` tinyint(1) DEFAULT NULL,
  `investigations_spermanalysis` tinyint(1) DEFAULT NULL,
  `investigations_notes` text,
  `treatment_bcp` tinyint(1) DEFAULT NULL,
  `treatment_bcp1` varchar(10) DEFAULT NULL,
  `treatment_cyklokapron` tinyint(1) DEFAULT NULL,
  `treatment_anaprox` tinyint(1) DEFAULT NULL,
  `treatment_mirena` tinyint(1) DEFAULT NULL,
  `treatment_hrt` tinyint(1) DEFAULT NULL,
  `treatment_surgery` tinyint(1) DEFAULT NULL,
  `treatment_vaginalestrogen` tinyint(1) DEFAULT NULL,
  `treatment_notes` text,
  `followup_weeks` tinyint(1) DEFAULT NULL,
  `followup_weeks1` varchar(10) DEFAULT NULL,
  `followup_afterinvestigations` tinyint(1) DEFAULT NULL,
  `followup_anaprox` tinyint(1) DEFAULT NULL,
  `provider_no` int(10) DEFAULT NULL,
  `formCreated` date DEFAULT NULL,
  `formEdited` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `year1` varchar(5) DEFAULT NULL,
  `year2` varchar(5) DEFAULT NULL,
  `year3` varchar(5) DEFAULT NULL,
  `year4` varchar(5) DEFAULT NULL,
  `bpi_date1` date DEFAULT NULL,
  `bpi_date2` date DEFAULT NULL,
  `bpi_date3` date DEFAULT NULL,
  `operation1` text,
  `operation2` text,
  `operation3` text,
  `operation4` text,
  `patient_fname` varchar(60) DEFAULT NULL,
  `patient_lname` varchar(60) DEFAULT NULL,
  `patient_age` varchar(15) DEFAULT NULL,
  `family_doctor_fname` varchar(60) DEFAULT NULL,
  `family_doctor_lname` varchar(60) DEFAULT NULL,
  `no_med_hist` varchar(2) DEFAULT '0',
  `no_investigations` varchar(2) DEFAULT '0',
  `no_treatments` varchar(2) DEFAULT '0',
  `no_allergies` VARCHAR(2),
  `no_current_medications` VARCHAR(2),
  `prn` varchar(2) DEFAULT NULL,
  `appt_date` date DEFAULT NULL,
  PRIMARY KEY (`ID`)
);